apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
      - name: restaurant-container
        image: restaurant-service:1.0
        ports:
        - containerPort: 8000

